import { auth, db } from "./firebase-refleksjon.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-auth.js";
import { doc, getDoc, setDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-firestore.js";

const seededPlan={title:"Kompakt lag & ro med ballen",date:"2026-09-02",focus:"Fjerne blindpasninger, holde bredde og forminske avstander mellom leddene.",intro:"Tre prinsipper: Fredet korridor gir tid til å se opp og holde bredde. Hele laget over midtlinjen krymper banen. I 1v1 skal vi presse aggressivt uten å rygge.",progression:"Uke 1–2: Kjør økten med full fredning.\nUke 3–4: Kanten har bare 3 sekunder fredning før forsvareren kan presse.\nUke 5–6: Fjern midtlinje-regelen. Bruk kampvideo til å kontrollere om stopperne holder laget kompakt frivillig.",sections:[
{title:"Praten i ringen",minutes:5,details:"Aktiver spillernes forståelse av fredet korridor, midtlinje-regelen og aggressivt press.",coaching:"Spør hvorfor vi bruker reglene. La spillerne formulere svarene selv."},
{title:"Fysisk start",minutes:10,details:"Lett jogg og dynamisk tøying for å gjøre kroppen klar.",coaching:"Kontrollert progresjon og god bevegelseskvalitet."},
{title:"1 mot 1 med pasning",minutes:10,details:"Bane 15 x 10 m. Angriper spiller over til forsvarer, som spurter direkte i press.",coaching:"Spurt–brems. Lavt i knærne, brems én meter før og styr angriperen utover."},
{title:"Rondo med jokere",minutes:10,details:"Bane 25 x 20 m. To jevne lag inne og jokere på linjene. Tilpass antallet. Maks to berøringer sentralt.",coaching:"Skann over skulderen før mottak. Bruk støttepasning bakover når det koker."},
{title:"Kantkombinasjon",minutes:30,details:"Bane 32 x 50 m. Back spiller kant foran figur, støtte inn til midtbane, og midtbane trer kant i bakrom. Fem meter langs linjen er fredet ved direkte pasning.",coaching:"Kant løfter blikket før innlegg. Spiss og motsatt kant fyller boksen. Sentral midtbane følger opp for andreball."},
{title:"Storspill",minutes:30,details:"Kampsimulering på 64 x 50 m. Fredede kanter fjernes. Mål teller bare når alle utespillere er over midtstreken.",coaching:"Stopperne styrer linjen høyt. Keeper står som sweeper rundt 16-meteren og plukker lange baller."}]};

const el=id=>document.getElementById(id);let currentUser=null;
function isoWeek(date=new Date()){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));const start=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d-start)/86400000)+1)/7)}
function setupWeeks(){const current=isoWeek();for(let offset=-2;offset<=8;offset++){const week=current+offset,option=document.createElement("option");option.value=`week${week}`;option.textContent=offset===0?`Denne uken · uke ${week}`:`Uke ${week}`;el("weekSelect").appendChild(option)}el("weekSelect").value=`week${current}`}
function addSection(section={}){const node=el("sectionTemplate").content.firstElementChild.cloneNode(true);node.querySelector(".partTitle").value=section.title||"";node.querySelector(".partMinutes").value=section.minutes??10;node.querySelector(".partDetails").value=section.details||"";node.querySelector(".partCoaching").value=section.coaching||"";node.querySelector(".removePart").onclick=()=>{node.remove();renumber();updateTotal()};node.querySelector(".partMinutes").oninput=updateTotal;el("sections").appendChild(node);renumber();updateTotal()}
function renumber(){[...el("sections").children].forEach((node,index)=>node.querySelector(".partNumber").textContent=String(index+1).padStart(2,"0"))}
function updateTotal(){el("totalMinutes").textContent=[...document.querySelectorAll(".partMinutes")].reduce((sum,input)=>sum+(Number(input.value)||0),0)}
function blankPlan(){return{title:"Ny treningsøkt",date:new Date().toISOString().slice(0,10),focus:"",intro:"",progression:"",sections:[]}}
function render(plan){el("titleInput").value=plan.title||"";el("dateInput").value=plan.date||"";el("focusInput").value=plan.focus||"";el("introInput").value=plan.intro||"";el("progressionInput").value=plan.progression||"";el("sections").innerHTML="";(plan.sections||[]).forEach(addSection);updateTotal()}
function collect(){return{title:el("titleInput").value.trim(),date:el("dateInput").value,focus:el("focusInput").value.trim(),intro:el("introInput").value.trim(),progression:el("progressionInput").value.trim(),sections:[...el("sections").children].map(node=>({title:node.querySelector(".partTitle").value.trim(),minutes:Number(node.querySelector(".partMinutes").value)||0,details:node.querySelector(".partDetails").value.trim(),coaching:node.querySelector(".partCoaching").value.trim()}))}}
async function loadPlan(){document.body.classList.add("loading");el("saveStatus").textContent="Henter …";try{const snap=await getDoc(doc(db,"weeklyExercises",el("weekSelect").value));if(snap.exists()&&Array.isArray(snap.data().sections))render(snap.data());else if(el("weekSelect").value===`week${isoWeek(new Date("2026-09-02T12:00:00"))}`)render(seededPlan);else render(blankPlan());el("saveStatus").textContent=snap.exists()?"Lagret plan":"Ikke lagret"}catch(error){console.error(error);el("saveStatus").textContent="Kunne ikke hente"}finally{document.body.classList.remove("loading")}}
el("planForm").onsubmit=async event=>{event.preventDefault();if(!currentUser)return;el("saveBtn").disabled=true;el("saveStatus").textContent="Lagrer …";try{const plan=collect();await setDoc(doc(db,"weeklyExercises",el("weekSelect").value),{...plan,exercises:plan.sections.map(section=>({title:section.title,video:""})),updatedAt:serverTimestamp(),updatedBy:currentUser.uid},{merge:true});el("saveStatus").textContent="Lagret nå";el("saveStatus").classList.add("saved")}catch(error){console.error(error);el("saveStatus").textContent="Lagring feilet";alert("Planen kunne ikke lagres. Kontroller Firestore-tilgangen.")}finally{el("saveBtn").disabled=false}};
el("weekSelect").onchange=loadPlan;el("addSectionBtn").onclick=()=>addSection();el("newPlanBtn").onclick=()=>{if(confirm("Starte med en tom plan for denne uken?"))render(blankPlan())};setupWeeks();
onAuthStateChanged(auth,async user=>{if(!user){location.href="./index.html";return}const profile=await getDoc(doc(db,"users",user.uid));if(!profile.exists()||profile.data().role!=="coach"){alert("Kun trener har tilgang.");location.href="./fremside.html";return}currentUser=user;await loadPlan()});
